import { useCallback, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ChevronRight, Download, ExternalLink, ShieldCheck, Smartphone } from "lucide-react-native";
import { router, useFocusEffect } from "expo-router";
import { useSQLiteContext } from "expo-sqlite";
import { BottomNav } from "../src/components/BottomNav";
import { Screen } from "../src/components/ui";
import { exportTransactions } from "../src/services/exportService";
import { isAssistantRoleAvailable, isAssistantRoleHeld, openAssistantSettings, requestAssistantRole } from "../src/services/assistantService";
import { useAppColors } from "../src/theme";

export default function SettingsScreen() {
  const colors = useAppColors();
  const db = useSQLiteContext();
  const [assistantAvailable, setAssistantAvailable] = useState(false);
  const [assistantHeld, setAssistantHeld] = useState(false);
  const loadRole = useCallback(async () => { setAssistantAvailable(await isAssistantRoleAvailable()); setAssistantHeld(await isAssistantRoleHeld()); }, []);
  useFocusEffect(useCallback(() => { void loadRole(); }, [loadRole]));

  async function activateAssistant() {
    if (assistantAvailable) { await requestAssistantRole(); await loadRole(); return; }
    Alert.alert("Assistente não disponível", "Este build precisa ser instalado como Development Build para expor a integração Android.", [{ text: "OK" }, { text: "Abrir configurações", onPress: () => { void openAssistantSettings(); } }]);
  }
  async function exportData() { try { const ok = await exportTransactions(db); if (!ok) Alert.alert("Compartilhamento indisponível", "Não foi possível abrir o compartilhamento neste aparelho."); } catch { Alert.alert("Não foi possível exportar", "Tente novamente."); } }

  return <View style={[styles.root, { backgroundColor: colors.background }]}><ScrollView contentContainerStyle={styles.scroll}><Screen scroll={false}><View style={styles.header}><Text style={[styles.eyebrow, { color: colors.textMuted }]}>PREFERÊNCIAS</Text><Text style={[styles.title, { color: colors.text }]}>Ajustes</Text></View><Text style={[styles.section, { color: colors.textMuted }]}>BACK TAP</Text><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardHeader}><View style={[styles.cardIcon, { backgroundColor: colors.accentSoft }]}><Smartphone color={colors.accent} size={20} /></View><View style={styles.cardCopy}><Text style={[styles.cardTitle, { color: colors.text }]}>Lançamento rápido</Text><Text style={[styles.cardDescription, { color: colors.textMuted }]}>{assistantHeld ? "Assistente ativo" : "Assistente não configurado"}</Text></View><View style={[styles.statusDot, { backgroundColor: assistantHeld ? colors.positive : colors.warning }]} /></View><Pressable accessibilityRole="button" onPress={() => void activateAssistant()} style={({ pressed }) => [styles.actionRow, { borderTopColor: colors.border, opacity: pressed ? 0.7 : 1 }]}><ShieldCheck color={colors.text} size={18} /><Text style={[styles.actionText, { color: colors.text }]}>{assistantHeld ? "Verificar assistente" : "Ativar lançamento por Back Tap"}</Text><ChevronRight color={colors.textMuted} size={18} /></Pressable></View><View style={[styles.help, { backgroundColor: colors.surfaceMuted }]}><Text style={[styles.helpTitle, { color: colors.text }]}>Como configurar</Text><Text style={[styles.helpText, { color: colors.textMuted }]}>1. Defina o TapFinance como assistente digital padrão.{"\n"}2. Abra as configurações de Back Tap do aparelho.{"\n"}3. Escolha Double back tap → Launch digital assistant.</Text><Pressable onPress={() => void openAssistantSettings()} style={styles.inline}><ExternalLink color={colors.accent} size={16} /><Text style={[styles.inlineText, { color: colors.accent }]}>Abrir configurações do assistente</Text></Pressable></View><Text style={[styles.section, { color: colors.textMuted, marginTop: 28 }]}>DADOS</Text><Pressable accessibilityRole="button" onPress={() => void exportData()} style={[styles.dataRow, { borderBottomColor: colors.border }]}><Download color={colors.text} size={19} /><View style={styles.cardCopy}><Text style={[styles.cardTitle, { color: colors.text }]}>Exportar dados</Text><Text style={[styles.cardDescription, { color: colors.textMuted }]}>CSV com seus lançamentos</Text></View><ChevronRight color={colors.textMuted} size={18} /></Pressable><Text style={[styles.privacy, { color: colors.textMuted }]}>Seus dados ficam neste aparelho. O TapFinance não usa conta, servidor ou nuvem.</Text></Screen></ScrollView><BottomNav /></View>;
}

const styles = StyleSheet.create({ root: { flex: 1 }, scroll: { paddingBottom: 24 }, header: { marginBottom: 34 }, eyebrow: { fontSize: 12, fontWeight: "700", letterSpacing: 1.8, marginBottom: 8 }, title: { fontSize: 28, fontWeight: "700", letterSpacing: -0.7 }, section: { fontSize: 12, fontWeight: "700", letterSpacing: 1.2, marginBottom: 10 }, card: { borderWidth: 1, borderRadius: 8, overflow: "hidden" }, cardHeader: { padding: 18, flexDirection: "row", alignItems: "center", gap: 12 }, cardIcon: { width: 40, height: 40, borderRadius: 8, alignItems: "center", justifyContent: "center" }, cardCopy: { flex: 1, gap: 4 }, cardTitle: { fontSize: 15, fontWeight: "700" }, cardDescription: { fontSize: 13 }, statusDot: { width: 9, height: 9, borderRadius: 5 }, actionRow: { borderTopWidth: 1, minHeight: 56, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 18 }, actionText: { flex: 1, fontSize: 14, fontWeight: "700" }, help: { borderRadius: 8, padding: 18, marginTop: 16, gap: 10 }, helpTitle: { fontSize: 15, fontWeight: "700" }, helpText: { fontSize: 14, lineHeight: 22 }, inline: { flexDirection: "row", alignItems: "center", gap: 7, minHeight: 44 }, inlineText: { fontSize: 13, fontWeight: "700" }, dataRow: { minHeight: 68, borderBottomWidth: 1, flexDirection: "row", alignItems: "center", gap: 12 }, privacy: { fontSize: 12, lineHeight: 18, marginTop: 24 } });
